(#39) 설정 UI 완성
mash-up-kr/mobalmobal_iOS pull request #73
Opened 2021-03-16 18:54 UTC by JeongMinHo

### Related Issue

resolve: #39 

### What does this PR do?
- 기본적인 설정 페이지 UI 구현

### Why are we doing this?
- UI는 구현되어있고 이제 각각 페이지로 넘어가는 것 구현해야 됨

2021-03-17 08:22 UTC, tngusmiso requested changes
이거 뭔가 문제가 생긴 것 같습니다,,,,!
changed files가 70개나 되고
기존에 있던 파일들이 중복으로 생성돼서 `filename 2` 이런식으로 생겨난 파일들이 엄청 많아요ㅠㅠ
어디서 꼬인지 한번 확인 해 봐야할 것 같습니당...

2021-03-18 08:45 UTC, JeongMinHo reviewed
중복 파일들 제거해서 다시 커밋했습니다 😃

2021-03-19 18:56 UTC, tngusmiso approved these changes
중복파일 몇가지 남아있는 게 있네용!!!!
* Account/AccountViewController 2.swift
* Assets.xcassets/Profile.imageset/Contents 2.json
* Assets.xcassets/arrowChevronBigRight.imageset/arrowChevronBigRight 2.png
* Assets.xcassets/chargingComplete.imageset/Contents 2.json
* Assets.xcassets/errorImage.imageset/Contents 2.json
* Assets.xcassets/iconlyLightCheckOn.imageset/Contents 3.json
* Assets.xcassets/iconlyLightEditSquare.imageset/Contents 2.json
* Assets.xcassets/iconlyLightMessage.imageset/Contents 3.json
* Assets.xcassets/iconlyLightProfile.imageset/Contents 3.json
* Assets.xcassets/iconlyLightSetting.imageset/Contents 2.json
* Assets.xcassets/menuCloseBig.imageset/Contents 2.json

중복파일 마지막으로 한번만 더 봐주시구....!
코멘트 달아둔거 확인 또는 수정하면 바로 머지해도 될 것 같습니당👍

2021-03-19 18:56 UTC, tngusmiso commented on MobalMobal/MobalMobal/Extension/UIColor+Additions.swift
> +        return UIColor(red: 255/255, green: 56/255, blue: 176/255, alpha: 1.0)
이렇게 쓰면 색 적용이 제대로 되지 않아요!
`255.0 / 255.0`처럼 float형으로 작성해주어야 합니다

2021-03-19 18:56 UTC, tngusmiso commented on MobalMobal/MobalMobal/Setting/SettingViewController.swift
> +    private func setConstraint() {
constraint 적용하는 부분은 함수를 만들어서 호출해도 되지만
[updateConstraints()](https://developer.apple.com/documentation/uikit/uiview/1622512-updateconstraints)를 오버라이드하는 방법으로 많이 사용한다고 합니다!
요건 나중에 선택사항으로 둬도 괜찮을 것 같아요

2021-04-02 17:23 UTC, JeongMinHo commented on MobalMobal/MobalMobal/Setting/SettingViewController.swift
> +    private func setConstraint() {
중복 파일은 다시 확인하고 삭제했습니다:)

2021-04-02 17:24 UTC, JeongMinHo commented on MobalMobal/MobalMobal/Extension/UIColor+Additions.swift
> +        return UIColor(red: 255/255, green: 56/255, blue: 176/255, alpha: 1.0)
Float 타입이긴 해도 저렇게 작성해도 됐었는데 이 부분은 한번 다시 확인해볼게요 👍

2021-04-02 17:24 UTC, JeongMinHo commented on MobalMobal/MobalMobal/Setting/SettingViewController.swift
> +    private func setConstraint() {
이 부분 내용 재성이형 답글에서 봤었는데 이 부분 한번 얘기해보면 좋을 것 같아여

2021-04-02 17:43 UTC, merged

2021-04-03 05:28 UTC, JeongMinHo commented on MobalMobal/MobalMobal/Extension/UIColor+Additions.swift
> +        return UIColor(red: 255/255, green: 56/255, blue: 176/255, alpha: 1.0)
해보니까 뒤에 굳이 .0 안붙여줘도 타입추론으로 자동 적용되는거 같아요!

2021-04-03 06:32 UTC, tngusmiso commented on MobalMobal/MobalMobal/Extension/UIColor+Additions.swift
> +        return UIColor(red: 255/255, green: 56/255, blue: 176/255, alpha: 1.0)
@JeongMinHo 
오호 UIColor initializer가 float만 인자로 받기 때문에 자동으로 추론해주는 걸까요? 나누기 연산 자체는 Int형을 반환하기 때문에 안될 거라고 생각했는데!

https://developer.apple.com/documentation/uikit/uicolor/1621925-init

https://developer.apple.com/documentation/swift/int/2884531

2021-04-03 19:19 UTC, JeongMinHo commented on MobalMobal/MobalMobal/Extension/UIColor+Additions.swift
> +        return UIColor(red: 255/255, green: 56/255, blue: 176/255, alpha: 1.0)
<img width="518" alt="스크린샷 2021-04-04 오전 4 16 37" src="https://user-images.githubusercontent.com/48345308/113489011-8e008400-94fc-11eb-8eb4-074af999253c.png">

이 부분 관련해서 자료 찾아보았는데, 이 글에서도 확실하지는 않지만 타입 추론이 적용되는 것 같다고 하네요,,

https://www.codingexplorer.com/create-uicolor-swift/